#!/usr/bin/env python3

import os
import sys

try:
    from pip import main as pipmain
except:
    from pip._internal import main as pipmain

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pipmain(['install', "-q", package])

import_or_install("keyring")
import keyring

if len(sys.argv) < 3 or not sys.argv[1] or not sys.argv[2]:
     print("Username and password are required")
     sys.exit()

username=sys.argv[1]
password=sys.argv[2]

keyring.set_password("git-tracking-username", "git-tracking-username", username)
keyring.set_password("git-tracking-password", "git-tracking-password", username)

print("Credentials were successfuly saved")
