#!/bin/bash

# END

username=$1
password=$2

[ -z "$username" ] && [ -z "$password" ] echo Username and password are required! && exit 1

security delete-generic-password -s git-set-redmine
security add-generic-password -a $username -s git-set-redmine -w $password
security find-generic-password -s git-set-redmine -w

echo "Credentials were successfuly saved"
